# Generated by Django 4.2 on 2023-04-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=100)),
                ('Cluster', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=100)),
                ('CellName', models.CharField(max_length=100)),
                ('Band', models.CharField(max_length=100)),
                ('AntennaHeight', models.CharField(max_length=10)),
                ('Azimuth', models.CharField(max_length=10)),
            ],
        ),
    ]
